import {describe,it,expect} from 'vitest';
import {awardSentryCharge,authorizeFranklinUltimate,canReleaseFranklin,consumeFranklinUltimate,createRescueWaveController,rescueEntryCharge,rescueEntryCheckpoint,rescueEntryRecord,rescueRetryRecord,rescueStage,rescueWaveCanSpawn,safeRescueSpawn,tickRescueWaves,RESCUE_RULES} from '../src/systems/RescueRules';
import {chooseWardenPortal,createWardenController,damageWarden,recheckWardenPortal,tickWarden,wardenAcceptedDamage,wardenCanAct,wardenClawShape,wardenDashTouchesRibs,wardenLineHitsRect,wardenSonicLine,wardenVulnerable,type WardenController} from '../src/systems/HollowWardenRules';

const snap={bossX:800,bossY:360,playerX:900,playerY:340,playerWidth:40,playerHeight:60};
function advanceTo(c:WardenController,phase:string){let n=c;for(let i=0;i<500&&n.phase!==phase;i++)n=tickWarden(n,50,snap);expect(n.phase).toBe(phase);return n;}

describe('Hollow Prison foundation rules',()=>{
 it('drains only at first-entry/replay checkpoint0 and preserves saved chained charge on reload/death',()=>{expect(rescueEntryCharge('chained',0,37)).toBe(0);expect(rescueEntryCharge('chained',180,37)).toBe(37);expect(rescueEntryCharge('chained',180,108)).toBe(100);expect(rescueEntryCharge('released',540,100)).toBe(0);expect(rescueEntryCharge('cleared',540,100)).toBe(0);expect(rescueEntryCheckpoint('chained')).toBe(180);expect(rescueEntryCheckpoint('released')).toBe(540);expect(rescueEntryCheckpoint('cleared')).toBe(540);expect(rescueStage({opened:[],bossDefeated:false})).toBe('chained');expect(rescueStage({opened:[0],bossDefeated:false})).toBe('released');expect(rescueStage({opened:[],bossDefeated:true})).toBe('cleared');});
 it('selects fresh dev previews independently and restores each stage on retry',()=>{const saved={checkpoint:540,charge:0,opened:[0],bossDefeated:true},fresh=rescueEntryRecord({devPreview:true,saved});expect(rescueStage(fresh)).toBe('chained');expect(rescueEntryCharge(rescueStage(fresh),fresh.checkpoint,fresh.charge)).toBe(0);const chained=rescueRetryRecord('chained',37),chainRetry=rescueEntryRecord({devPreview:true,retry:true,...chained,saved});expect(chainRetry.charge).toBe(37);expect(rescueEntryCharge(rescueStage(chainRetry),chainRetry.checkpoint,chainRetry.charge)).toBe(37);const released=rescueRetryRecord('released',80),releasedRetry=rescueEntryRecord({devPreview:true,retry:true,...released,saved});expect(rescueStage(releasedRetry)).toBe('released');expect(releasedRetry.charge).toBe(0);const replay=rescueEntryRecord({devPreview:true,bossPreview:false,retry:false,checkpoint:0,charge:0,opened:[],bossDefeated:false,saved});expect(rescueStage(replay)).toBe('chained');});
 it('rearms once per accepted full real U so wasted casts can recharge and retry',()=>{const base={stage:'chained' as const,attack:'ultimate' as const,charge:100,playerX:540,playerY:340};expect(canReleaseFranklin(base)).toBe(true);expect(canReleaseFranklin({...base,charge:99})).toBe(false);expect(canReleaseFranklin({...base,attack:'dash'})).toBe(false);expect(canReleaseFranklin({...base,playerX:701})).toBe(false);expect(canReleaseFranklin({...base,playerY:451})).toBe(false);let auth=authorizeFranklinUltimate({armed:false,consumed:false},false,100);expect(auth.armed).toBe(false);auth=authorizeFranklinUltimate(auth,true,99);expect(auth.armed).toBe(false);auth=authorizeFranklinUltimate(auth,true,100);expect(auth.armed).toBe(true);const missed=consumeFranklinUltimate(auth,{stage:'chained',playerX:800,playerY:340});expect(missed.released).toBe(false);expect(missed.authorization.consumed).toBe(true);auth=authorizeFranklinUltimate(missed.authorization,false,100);expect(auth.armed).toBe(false);auth=authorizeFranklinUltimate(auth,true,100);expect(auth.armed).toBe(true);const released=consumeFranklinUltimate(auth,{stage:'chained',playerX:540,playerY:340});expect(released.released).toBe(true);expect(consumeFranklinUltimate(released.authorization,{stage:'chained',playerX:540,playerY:340}).released).toBe(false);expect(awardSentryCharge(95,'chained',true)).toBe(100);expect(awardSentryCharge(20,'released',true)).toBe(20);expect(awardSentryCharge(20,'chained',false)).toBe(20);expect(rescueWaveCanSpawn('chained',99,2)).toBe(true);expect(rescueWaveCanSpawn('chained',100,0)).toBe(false);expect(rescueWaveCanSpawn('chained',0,3)).toBe(false);expect(rescueWaveCanSpawn('released',0,0)).toBe(false);expect(RESCUE_RULES.maxEnemies).toBe(3);});
 it('keeps proposed arrival cues outside the danger radius using the farthest safe fallback',()=>{expect(safeRescueSpawn(780,780)).toBe(160);expect(safeRescueSpawn(780,200)).toBe(780);expect(safeRescueSpawn(400,400)).toBe(1070);});
 it('bounds live plus pending waves, relocates warned spawns with a fresh cue, and resumes after wasted U',()=>{let c=createRescueWaveController();let r=tickRescueWaves(c,{deltaMs:50,stage:'chained',charge:0,playerX:540,liveEnemies:0});c=r.controller;expect(c.pending).toHaveLength(2);expect(c.pending.length).toBeLessThanOrEqual(RESCUE_RULES.maxEnemies);const before=c.pending[0];r=tickRescueWaves(c,{deltaMs:50,stage:'chained',charge:0,playerX:before.x,liveEnemies:0});expect(r.controller.pending[0]).toMatchObject({x:before.x===160?1070:160,feetY:360,cueRemainingMs:700});r=tickRescueWaves(c,{deltaMs:50,stage:'chained',charge:100,playerX:540,liveEnemies:0});expect(r.controller.pending[0].cueRemainingMs).toBe(700);c=r.controller;r=tickRescueWaves(c,{deltaMs:50,stage:'chained',charge:99,playerX:540,liveEnemies:0});expect(r.controller.pending[0].cueRemainingMs).toBe(650);});
 it('holds ready pending arrivals at full charge but still completes and heals an empty wave',()=>{const spawn={x:900,feetY:360,kind:'normal' as const,patrolHalfWidth:50},held=tickRescueWaves({...createRescueWaveController(),pending:[{...spawn,cueRemainingMs:1}],spawnedThisWave:1},{deltaMs:50,stage:'chained',charge:100,playerX:500,liveEnemies:0});expect(held.activated).toHaveLength(0);expect(held.controller.pending[0].cueRemainingMs).toBe(1);const ready=tickRescueWaves(held.controller,{deltaMs:50,stage:'chained',charge:99,playerX:500,liveEnemies:0});expect(ready.activated[0]).toMatchObject(spawn);const complete=tickRescueWaves({...createRescueWaveController(),spawnedThisWave:1},{deltaMs:50,stage:'chained',charge:100,playerX:500,liveEnemies:0});expect(complete.waveCompleted).toBe(true);});
 it('cycles all four authored waves for ten sentry hits and still heals the final wave at full charge',()=>{let c=createRescueWaveController(),charge=0,hearts=1,spawns=0,completed=0;for(let frame=0;frame<1600&&completed<4;frame++){const r=tickRescueWaves(c,{deltaMs:50,stage:'chained',charge,playerX:0,liveEnemies:0});c=r.controller;spawns+=r.activated.length;for(let i=0;i<r.activated.length;i++)charge=awardSentryCharge(charge,'chained',true);if(r.waveCompleted){completed++;hearts=Math.min(3,hearts+.5);}}expect(spawns).toBe(10);expect(completed).toBe(4);expect(hearts).toBe(3);expect(charge).toBe(100);expect(c.waveIndex).toBe(0);expect(c.waitMs).toBe(900);expect(c.remaining).toHaveLength(0);expect(c.pending).toHaveLength(0);});
 it('caps elapsed time, freezes when inactive, and advances at most one phase per tick',()=>{let c=createWardenController();expect(tickWarden(c,5000,snap).elapsedMs).toBe(50);expect(tickWarden(c,50,{...snap,paused:true})).toEqual(c);for(let i=0;i<40;i++)c=tickWarden(c,50,snap);expect(c.phase).toBe('listen');expect(c.elapsedMs).toBe(0);});
 it('gates every Warden effect while hidden, inactive, dead, or paused',()=>{expect(wardenCanAct({})).toBe(true);expect(wardenCanAct({hidden:true})).toBe(false);expect(wardenCanAct({sceneActive:false})).toBe(false);expect(wardenCanAct({playerActive:false})).toBe(false);expect(wardenCanAct({paused:true})).toBe(false);});
 it('freezes hidden/dead timers and captures cue duration across the phase threshold',()=>{let c=advanceTo(createWardenController(),'claw-cue');expect(c.durationMs).toBe(900);c=damageWarden(c,16);expect(c.phaseTwo).toBe(true);expect(c.durationMs).toBe(900);expect(tickWarden(c,50,{...snap,hidden:true})).toEqual(c);expect(tickWarden(c,50,{...snap,dead:true})).toEqual(c);for(let i=0;i<18;i++)c=tickWarden(c,50,snap);expect(c.phase).toBe('claw-active');});
 it('locks claw direction and sonic geometry at cue entry',()=>{let c=advanceTo(createWardenController(),'claw-cue');c=tickWarden(c,50,{...snap,playerX:700});expect(c.lockedDirection).toBe(1);const rect=wardenClawShape(800,1);expect(rect).toEqual({x:800,y:300,width:220,height:60});let s=advanceTo(createWardenController(),'sonic-cue');const aim=wardenSonicLine(s,800);s=tickWarden(s,50,{...snap,playerX:1200});expect(wardenSonicLine(s,800)).toEqual(aim);expect(wardenLineHitsRect(aim,{x:890,y:330,width:20,height:30})).toBe(true);});
 it('cycles claw, sonic, portal and gives phase two sonic a second independently aimed warning',()=>{let c=advanceTo(createWardenController(),'listen');c=advanceTo(c,'claw-cue');c=advanceTo(c,'listen');c=advanceTo(c,'sonic-cue');c=advanceTo(c,'listen');c=advanceTo(c,'portal-cue');let p=createWardenController(16);p=advanceTo(p,'listen');p=advanceTo(p,'claw-cue');expect(p.durationMs).toBe(800);p=advanceTo(p,'listen');p=advanceTo(p,'sonic-cue');p=advanceTo(p,'sonic-active');p={...p,elapsedMs:p.durationMs-50};p=tickWarden(p,50,{...snap,playerX:1234,playerY:210});expect(p.phase).toBe('sonic-cue');expect(p.sonicPass).toBe(1);expect(p.durationMs).toBe(900);expect(p.lockedAimX).toBe(1234);expect(p.lockedAimY).toBe(210);});
 it('selects farthest eligible portal, tie breaks left, and resets unsafe real warning before transfer',()=>{expect(chooseWardenPortal(980,960)).toBe(320);let c=createWardenController();c={...c,phase:'portal-cue',elapsedMs:c.durationMs-50,lockedPortalX:1640};c=tickWarden(c,50,{...snap,playerX:1640});expect(c.phase).toBe('portal-cue');expect(c.elapsedMs).toBe(0);expect(c.lockedPortalX).toBe(320);c={...c,phase:'portal-cue',durationMs:50,elapsedMs:0,lockedPortalX:320};c=tickWarden(c,50,{...snap,playerX:1000});expect(c.phase).toBe('portal-transfer');expect(recheckWardenPortal(c,800,1000)).toEqual({safe:true,destination:320});});
 it('opens damage only in gold recovery and uses the same radius-44 rib contact for dash and jump K',()=>{let c=createWardenController();expect(wardenAcceptedDamage(c,{attack:'ultimate',bossX:800,playerX:800,playerY:220,cooldownMs:0})).toBe(0);c={...c,phase:'claw-recovery'};expect(wardenVulnerable(c)).toBe(true);expect(wardenDashTouchesRibs(800,840,230)).toBe(true);expect(wardenDashTouchesRibs(800,840,340)).toBe(false);expect(wardenAcceptedDamage(c,{attack:'jump-k',bossX:800,playerX:840,playerY:230,cooldownMs:0})).toBe(2);expect(wardenAcceptedDamage(c,{attack:'dash',bossX:800,playerX:840,playerY:230,cooldownMs:0})).toBe(2);expect(wardenAcceptedDamage(c,{attack:'ultimate',bossX:800,playerX:1000,playerY:340,cooldownMs:0})).toBe(8);expect(wardenAcceptedDamage(c,{attack:'ultimate',bossX:800,playerX:800,playerY:220,cooldownMs:450})).toBe(0);expect(wardenAcceptedDamage(c,{attack:'throw',bossX:800,playerX:800,playerY:220,cooldownMs:0})).toBe(0);expect(damageWarden(c,32).phase).toBe('defeated');expect(wardenVulnerable(damageWarden(c,32))).toBe(false);});
});
