import {describe,expect,it} from 'vitest';
import {createFranklinController,damageFranklin,franklinAcceptedChargeDamage,franklinCanAct,franklinChipBounds,franklinChipHealth,franklinCrash,franklinPillarSafeGaps,franklinTailWaveBounds,resumeFranklinWarning,tickFranklin,FRANKLIN_RULES,FRANKLIN_VISUAL,type FranklinController} from '../src/systems/FranklinFireFoxRules';

const snap={playerX:1200,playerY:300,bossX:790};
function until(c:ReturnType<typeof createFranklinController>,phase:string){for(let i=0;i<1200&&c.phase!==phase;i++)c=tickFranklin(c,50,snap);expect(c.phase).toBe(phase);return c;}
describe('Franklin rescue controller',()=>{
 it('gates inactive scenes and caps time, starts the warning only after intro',()=>{let c=createFranklinController();expect(tickFranklin(c,9000,snap).elapsed).toBe(50);expect(tickFranklin(c,50,{...snap,paused:true})).toEqual(c);c=until(c,'pounce-cue');expect(c.elapsed).toBe(0);});
 it('keeps Franklin hittable through the main fight and starts overdrive at half health',()=>{let c=createFranklinController();c.phase='pounce-cue';c=damageFranklin(c,16);expect(c).toMatchObject({hp:16,phase2:true});c=damageFranklin(c,50);expect(c).toMatchObject({hp:6,phase:'collapse'});});
 it('restarts interrupted attacks with a full warning and discards active hazards',()=>{let c={...createFranklinController(),phase:'pillars' as const,hazards:[400,700]};expect(resumeFranklinWarning(c)).toMatchObject({phase:'pillars-cue',elapsed:0,hazards:[]});});
 it('locks pillar markers at cue entry and computes safe corridors',()=>{let c=until(createFranklinController(),'pillars-cue');c=tickFranklin(c,50,{...snap,playerX:1040});const markers=[...c.hazards];c=tickFranklin(c,50,{...snap,playerX:1600});expect(c.hazards).toEqual(markers);expect(franklinPillarSafeGaps(markers).every(x=>x.right-x.left>=100)).toBe(true);});
 it('uses all four phase-one attacks and resists only after two complete cycles',()=>{let c=until(createFranklinController(),'pounce-cue');const cycle=()=>{c=until(c,'barrage-cue');c=until(c,'tail-cue');c=until(c,'tail');c=until(c,'pillars-cue');c=until(c,'pillars');for(let i=0;i<200&&c.phase!=='pounce-cue'&&c.phase!=='resistance';i++)c=tickFranklin(c,50,snap);};cycle();expect(c).toMatchObject({phase:'pounce-cue',cycles:1});cycle();expect(c).toMatchObject({phase:'resistance',cycles:0});expect(FRANKLIN_RULES.resistanceAfterCycles).toBe(2);});
 it('keeps overdrive chains deterministic with readable minimum cues',()=>{let c=until(damageFranklin({...createFranklinController(),phase:'pounce-cue'},16),'pounce-cue');c=until(c,'wallbounce-cue');expect(c.phase2).toBe(true);expect(c.phase).toBe('wallbounce-cue');expect(FRANKLIN_RULES.overdrivePounceTellMs).toBeGreaterThanOrEqual(650);c=until(c,'wallbounce');c=until(c,'pounce-cue');c=until(c,'barrage-cue');c=until(c,'pillars-cue');c=until(c,'tail-cue');expect(c.phase).toBe('tail-cue');expect(FRANKLIN_RULES.overdriveTailTellMs).toBeGreaterThanOrEqual(650);});
 it('uses the same traveling tail rectangle for rendering and collision',()=>{const c={...createFranklinController(),phase:'tail' as const,aimX:800,direction:1,elapsed:500};expect(franklinTailWaveBounds(c)).toEqual({left:940,right:1000,top:332,bottom:360});});
 it('requires three clean wall crashes before opening the chip stomp',()=>{let c:FranklinController={...createFranklinController(),phase:'final-charge'};c=franklinAcceptedChargeDamage(c);c=franklinCrash(c,!c.damagedDuringCharge);expect(c.cleanCrashes).toBe(0);c={...c,phase:'final-charge'};c=franklinCrash(c,true);c={...c,phase:'final-charge'};c=franklinCrash(c,true);c={...c,phase:'final-charge'};c=franklinCrash(c,true);expect(c.cleanCrashes).toBe(3);expect(until(c,'safe-chip').phase).toBe('safe-chip');});
 it('cannot damage or skip ahead during the chip objective',()=>{const c={...createFranklinController(),phase:'safe-chip' as const,cleanCrashes:1};expect(damageFranklin(c,32)).toMatchObject({hp:32,phase:'safe-chip',cleanCrashes:1});expect(franklinCrash(c,true)).toMatchObject({phase:'safe-chip',cleanCrashes:1});});
 it('matches Duckoman visual dimensions and places the implant from the scaled source anchor',()=>{expect(FRANKLIN_VISUAL.referenceWidth).toBe(66);expect(FRANKLIN_VISUAL.referenceHeight).toBeCloseTo(50.51,2);expect(FRANKLIN_VISUAL.bodyWidth).toBe(46);expect(FRANKLIN_VISUAL.bodyHeight).toBe(40);const right=franklinChipBounds(800),left=franklinChipBounds(800,true);expect(right.left).toBeCloseTo(784.6);expect(right.right).toBeCloseTo(806.6);expect(right.top).toBeCloseTo(315.7083);expect(right.bottom).toBeCloseTo(333.7083);expect(left.left).toBeCloseTo(793.4);expect(left.right).toBeCloseTo(815.4);});
 it('shows chip health through failed and clean crashes, then empties only when rescued',()=>{let c=createFranklinController();expect(franklinChipHealth(c)).toBe(32);c={...c,hp:6,phase:'collapse'};expect(franklinChipHealth(c)).toBe(6);c={...c,phase:'crash',cleanCrashes:0};expect(franklinChipHealth(c)).toBe(6);c={...c,phase:'final-cue',cleanCrashes:1};expect(franklinChipHealth(c)).toBe(4);c={...c,phase:'crash',cleanCrashes:2};expect(franklinChipHealth(c)).toBe(2);c={...c,phase:'safe-chip',cleanCrashes:3};expect(franklinChipHealth(c)).toBe(1);c={...c,phase:'rescued',rescued:true};expect(franklinChipHealth(c)).toBe(0);});
 it('keeps each encounter controller independent',()=>{expect(createFranklinController()).not.toBe(createFranklinController());expect(franklinCanAct({hidden:true})).toBe(false);});
});
