import {describe,it,expect} from 'vitest';
import {RouteAttempt} from '../src/systems/RouteAttempt';

const frame=(overrides:Partial<{localX:number;intent:boolean;active:boolean;visible:boolean;alive:boolean;assisted:boolean}>={})=>({localX:200,intent:false,active:true,visible:true,alive:true,assisted:false,...overrides});
const start=(attempt:RouteAttempt)=>attempt.tick(16,frame({localX:100,intent:true}));

describe('RouteAttempt',()=>{
 it('starts only on intentional action at local x 100 or later',()=>{const run=new RouteAttempt();run.tick(100,frame({intent:false}));run.tick(100,frame({localX:99,intent:true}));expect(run.state).toBe('waiting');expect(run.elapsedMs).toBe(0);run.tick(25,frame({localX:100,intent:true}));expect(run.state).toBe('running');expect(run.elapsedMs).toBe(25);});
 it('accepts rings once and only in authored order',()=>{const run=new RouteAttempt();start(run);expect(run.collectRing(1)).toBe(false);expect(run.collectRing(0)).toBe(true);expect(run.collectRing(0)).toBe(false);expect(run.collectRing(2)).toBe(false);expect(run.collectRing(1)).toBe(true);expect(run.collectRing(2)).toBe(true);expect(run.nextRing).toBe(3);});
 it('marks an incomplete right exit missed and resets on left exit',()=>{const run=new RouteAttempt();start(run);run.collectRing(0);expect(run.tick(16,frame({localX:1440}))).toBe('missed');expect(run.finish(1400)).toBeUndefined();expect(run.tick(16,frame({localX:-1}))).toBe('waiting');expect(run.nextRing).toBe(0);expect(run.elapsedMs).toBe(0);});
 it('counts damage only during a running attempt',()=>{const run=new RouteAttempt();run.damage();expect(run.hits).toBe(0);start(run);run.damage();expect(run.hits).toBe(1);run.abort();run.damage();expect(run.hits).toBe(1);});
 it('finishes only after three rings at the finish line, and only once',()=>{const run=new RouteAttempt();start(run);run.tick(80,frame());for(let i=0;i<3;i++)expect(run.collectRing(i)).toBe(true);expect(run.finish(1369)).toBeUndefined();expect(run.finish(1370)).toEqual({victory:true,elapsedMs:96,hits:0,eligible:true});expect(run.state).toBe('complete');expect(run.finish(1400)).toBeUndefined();});
 it('keeps a fully collected run active across a swept right boundary and includes its final delta',()=>{const run=new RouteAttempt();start(run);for(let i=0;i<3;i++)run.collectRing(i);expect(run.tick(50,frame({localX:1450}))).toBe('running');expect(run.elapsedMs).toBe(66);expect(run.finish(Number.NaN)).toBeUndefined();expect(run.finish(1450)).toMatchObject({victory:true,elapsedMs:66});run.reset();start(run);for(let i=0;i<3;i++)run.collectRing(i);expect(run.finish(1450)?.victory).toBe(true);});
 it('fails on death or abort without a victory',()=>{const death=new RouteAttempt();start(death);expect(death.tick(16,frame({alive:false}))).toBe('failed');expect(death.finish(1400)).toBeUndefined();const aborted=new RouteAttempt();start(aborted);aborted.abort();expect(aborted.state).toBe('failed');expect(aborted.finish(1400)).toBeUndefined();});
 it('excludes hidden, paused, and first-resumed-frame time',()=>{const run=new RouteAttempt();start(run);expect(run.elapsedMs).toBe(16);run.tick(1000,frame({active:false}));run.tick(1000,frame({visible:false}));run.tick(5000,frame());expect(run.elapsedMs).toBe(16);run.tick(20,frame());expect(run.elapsedMs).toBe(36);});
 it('keeps assist ineligibility sticky across retries and clears attempt state on reset',()=>{const run=new RouteAttempt();start(run);run.collectRing(0);run.damage();run.tick(16,frame({assisted:true}));run.reset();expect(run.state).toBe('waiting');expect(run.nextRing).toBe(0);expect(run.hits).toBe(0);expect(run.elapsedMs).toBe(0);expect(run.eligible).toBe(false);start(run);for(let i=0;i<3;i++)run.collectRing(i);expect(run.finish(1400)).toMatchObject({victory:true,eligible:false});});
});
