export const RESCUE_PRESSURE_RATIO=2.0736/1.728;
export const WARDEN_WALK_SPEED=85*RESCUE_PRESSURE_RATIO;
export const WARDEN_RULES={hp:32,phaseTwoAt:16,introMs:2000,listenMs:700/RESCUE_PRESSURE_RATIO,phaseTwoListenMs:550/RESCUE_PRESSURE_RATIO,clawCueMs:900,phaseTwoClawCueMs:800,clawActiveMs:240,clawRecoveryMs:1000,phaseTwoClawRecoveryMs:900,sonicCueMs:1000,phaseTwoSonicCueMs:900,phaseTwoSecondSonicCueMs:900,sonicActiveMs:180,sonicRecoveryMs:1300,phaseTwoSonicRecoveryMs:1150,portalCueMs:1100,phaseTwoPortalCueMs:1000,phaseTwoPortalFeintMs:600,portalTransferMs:220,portalClawCueMs:800,portalClawRecoveryMs:1150,hitCooldownMs:450,portalAnchors:[320,960,1640] as const,arena:{left:100,right:1900},claw:{left:0,right:220,top:300,bottom:360,damage:.5},beam:{thickness:16,damage:1,length:2500},rib:{x:26,top:180,bottom:270,radius:44},damage:{jumpK:2,ultimate:8},ultimateRangeX:210,ultimateRangeY:160} as const;
export type WardenAttack='claw'|'sonic'|'portal';
export type WardenPhase='introduction'|'listen'|'claw-cue'|'claw-active'|'claw-recovery'|'sonic-cue'|'sonic-active'|'sonic-recovery'|'portal-feint'|'portal-cue'|'portal-transfer'|'portal-claw-cue'|'portal-claw-active'|'portal-claw-recovery'|'recovery'|'defeated';
export interface WardenController {phase:WardenPhase;elapsedMs:number;durationMs:number;hp:number;attackIndex:number;phaseTwo:boolean;lockedDirection:-1|1;lockedAimX:number;lockedAimY:number;lockedPortalX?:number;sonicPass:number;}
export interface WardenSnapshot {bossX:number;bossY:number;playerX:number;playerY:number;playerWidth:number;playerHeight:number;paused?:boolean;hidden?:boolean;dead?:boolean;}
export function cappedActorDeltaMs(deltaMs:number,active:boolean):number{return active&&Number.isFinite(deltaMs)&&deltaMs>0?Math.min(50,deltaMs):0;}
export function breathingDisplayHeight(displayWidth:number,sourceWidth:number,sourceHeight:number,breath:number):number{return displayWidth*sourceHeight/sourceWidth*Math.max(.9,Math.min(1.1,breath));}
export function resumeChargeTell<T extends 'idle'|'warn'|'charge'|'rest'>(phase:T):T|'warn'{return phase==='warn'||phase==='charge'?'warn':phase;}
export function wardenCanAct(input:{hidden?:boolean;sceneActive?:boolean;playerActive?:boolean;paused?:boolean}):boolean{return !input.hidden&&input.sceneActive!==false&&input.playerActive!==false&&!input.paused;}
export function createWardenController(hp:number=WARDEN_RULES.hp):WardenController{const c={phase:hp<=0?'defeated' as const:'introduction' as const,elapsedMs:0,durationMs:0,hp:Math.max(0,hp),attackIndex:0,phaseTwo:hp<=WARDEN_RULES.phaseTwoAt,lockedDirection:1 as const,lockedAimX:0,lockedAimY:0,sonicPass:0};c.durationMs=duration(c);return c;}
export function damageWarden(c:WardenController,damage:number):WardenController {if(c.phase==='defeated'||!Number.isFinite(damage)||damage<=0)return {...c};const hp=Math.max(0,c.hp-damage);return {...c,hp,phase:hp===0?'defeated':c.phase,phaseTwo:hp<=WARDEN_RULES.phaseTwoAt};}
function duration(c:WardenController):number {const p=c.phaseTwo;switch(c.phase){case'introduction':return WARDEN_RULES.introMs;case'listen':return p?WARDEN_RULES.phaseTwoListenMs:WARDEN_RULES.listenMs;case'claw-cue':return p?WARDEN_RULES.phaseTwoClawCueMs:WARDEN_RULES.clawCueMs;case'claw-active':case'portal-claw-active':return WARDEN_RULES.clawActiveMs;case'claw-recovery':return p?WARDEN_RULES.phaseTwoClawRecoveryMs:WARDEN_RULES.clawRecoveryMs;case'sonic-cue':return c.sonicPass?WARDEN_RULES.phaseTwoSecondSonicCueMs:(p?WARDEN_RULES.phaseTwoSonicCueMs:WARDEN_RULES.sonicCueMs);case'sonic-active':return WARDEN_RULES.sonicActiveMs;case'sonic-recovery':return p?WARDEN_RULES.phaseTwoSonicRecoveryMs:WARDEN_RULES.sonicRecoveryMs;case'portal-feint':return WARDEN_RULES.phaseTwoPortalFeintMs;case'portal-cue':return p?WARDEN_RULES.phaseTwoPortalCueMs:WARDEN_RULES.portalCueMs;case'portal-transfer':return WARDEN_RULES.portalTransferMs;case'portal-claw-cue':return WARDEN_RULES.portalClawCueMs;case'portal-claw-recovery':return WARDEN_RULES.portalClawRecoveryMs;case'recovery':return p?WARDEN_RULES.phaseTwoSonicRecoveryMs:WARDEN_RULES.sonicRecoveryMs;default:return Infinity;}}
/** Restart only an interrupted tell/active phase; preserve its captured target geometry. */
export function resumeWardenWarning(c:WardenController):WardenController {
 let phase=c.phase;
 if(phase==='claw-active')phase='claw-cue';else if(phase==='sonic-active')phase='sonic-cue';else if(phase==='portal-feint'||phase==='portal-transfer')phase='portal-cue';else if(phase==='portal-claw-active')phase='portal-claw-cue';
 if(phase===c.phase)return {...c};
 const next={...c,phase,elapsedMs:0,durationMs:0};next.durationMs=duration(next);return next;
}
function enter(c:WardenController,phase:WardenPhase,s:WardenSnapshot):WardenController {const n={...c,phase,elapsedMs:0,durationMs:0};if(phase==='claw-cue'||phase==='portal-claw-cue')n.lockedDirection=s.playerX<s.bossX?-1:1;if(phase==='sonic-cue'){n.lockedAimX=s.playerX;n.lockedAimY=s.playerY;}n.durationMs=duration(n);return n;}
function transition(c:WardenController,s:WardenSnapshot):WardenController {switch(c.phase){case'introduction':return enter(c,'listen',s);case'listen':{const attack=(['claw','sonic','portal'] as const)[c.attackIndex%3];let n={...c,attackIndex:(c.attackIndex+1)%3,sonicPass:0};if(attack==='claw')return enter(n,'claw-cue',s);if(attack==='sonic')return enter(n,'sonic-cue',s);n=enter(n,c.phaseTwo?'portal-feint':'portal-cue',s);n.lockedPortalX=chooseWardenPortal(s.bossX,s.playerX);return n;}case'claw-cue':return enter(c,'claw-active',s);case'claw-active':return enter(c,'claw-recovery',s);case'claw-recovery':return enter(c,'listen',s);case'sonic-cue':return enter(c,'sonic-active',s);case'sonic-active':if(c.phaseTwo&&c.sonicPass===0){const n=enter({...c,sonicPass:1},'sonic-cue',s);return n;}return enter(c,'sonic-recovery',s);case'sonic-recovery':return enter(c,'listen',s);case'portal-feint':{const dest=chooseWardenPortal(s.bossX,s.playerX,WARDEN_RULES.portalAnchors,c.lockedPortalX)??chooseWardenPortal(s.bossX,s.playerX);const n=enter(c,'portal-cue',s);n.lockedPortalX=dest;return n;}case'portal-cue':{const check=recheckWardenPortal(c,s.bossX,s.playerX);if(!check.safe){const n=enter(c,'portal-cue',s);n.lockedPortalX=check.destination;return n;}return enter(c,'portal-transfer',s);}case'portal-transfer':return enter(c,'portal-claw-cue',s);case'portal-claw-cue':return enter(c,'portal-claw-active',s);case'portal-claw-active':return enter(c,'portal-claw-recovery',s);case'portal-claw-recovery':return enter(c,'listen',s);default:return c;}}
/** One bounded state transition at most per call; cue geometry/duration are captured on entry. */
export function tickWarden(c:WardenController,deltaMs:number,s:WardenSnapshot):WardenController {if(c.phase==='defeated'||s.paused||s.hidden||s.dead)return {...c};const dt=cappedActorDeltaMs(deltaMs,true);if(!dt)return {...c};const next={...c,elapsedMs:c.elapsedMs+dt};return next.elapsedMs>=c.durationMs?transition(next,s):next;}
export interface WardenRect {x:number;y:number;width:number;height:number;}
export interface WardenLine {x1:number;y1:number;x2:number;y2:number;thickness:number;}
export function wardenClawShape(bossX:number,direction:-1|1):WardenRect{return {x:direction===1?bossX+WARDEN_RULES.claw.left:bossX-WARDEN_RULES.claw.right,y:WARDEN_RULES.claw.top,width:WARDEN_RULES.claw.right-WARDEN_RULES.claw.left,height:WARDEN_RULES.claw.bottom-WARDEN_RULES.claw.top};}
export function wardenSonicLine(c:WardenController,bossX:number):WardenLine{let dx=c.lockedAimX-bossX,dy=c.lockedAimY-220,len=Math.hypot(dx,dy);if(len<1){dx=0;dy=1;len=1;}return {x1:bossX,y1:220,x2:bossX+dx/len*WARDEN_RULES.beam.length,y2:220+dy/len*WARDEN_RULES.beam.length,thickness:WARDEN_RULES.beam.thickness};}
export function wardenLineHitsRect(line:WardenLine,r:WardenRect):boolean {const pad=line.thickness/2,xmin=r.x-pad,xmax=r.x+r.width+pad,ymin=r.y-pad,ymax=r.y+r.height+pad,dx=line.x2-line.x1,dy=line.y2-line.y1;let lo=0,hi=1;for(const [p,q] of [[-dx,line.x1-xmin],[dx,xmax-line.x1],[-dy,line.y1-ymin],[dy,ymax-line.y1]] as const){if(p===0){if(q<0)return false;continue;}const t=q/p;if(p<0)lo=Math.max(lo,t);else hi=Math.min(hi,t);if(lo>hi)return false;}return true;}
export function wardenRectHitsRect(a:WardenRect,b:WardenRect):boolean{return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;}
export function wardenRibBounds(bossX:number):WardenRect{return {x:bossX-WARDEN_RULES.rib.x,y:WARDEN_RULES.rib.top,width:WARDEN_RULES.rib.x*2,height:WARDEN_RULES.rib.bottom-WARDEN_RULES.rib.top};}
export function wardenDashTouchesRibs(bossX:number,playerCenterX:number,playerCenterY:number,radius=WARDEN_RULES.rib.radius):boolean{const r=wardenRibBounds(bossX),cx=Math.max(r.x,Math.min(r.x+r.width,playerCenterX)),cy=Math.max(r.y,Math.min(r.y+r.height,playerCenterY));return (cx-playerCenterX)**2+(cy-playerCenterY)**2<=radius**2;}
export function chooseWardenPortal(bossX:number,playerX:number,anchors:readonly number[]=WARDEN_RULES.portalAnchors,exclude?:number):number|undefined{return [...anchors].filter(x=>x!==exclude&&x>=WARDEN_RULES.arena.left&&x<=WARDEN_RULES.arena.right&&Math.abs(x-playerX)>=220&&Math.abs(x-bossX)>=160).sort((a,b)=>Math.abs(b-bossX)-Math.abs(a-bossX)||a-b)[0];}
export function recheckWardenPortal(c:WardenController,bossX:number,playerX:number):{safe:boolean;destination?:number}{const dest=c.lockedPortalX;if(dest===undefined)return {safe:false};if(Math.abs(dest-playerX)>=220)return {safe:true,destination:dest};const next=chooseWardenPortal(bossX,playerX,WARDEN_RULES.portalAnchors,dest);return {safe:false,destination:next};}
export function wardenVulnerable(c:WardenController):boolean{return c.phase==='claw-recovery'||c.phase==='sonic-recovery'||c.phase==='portal-claw-recovery';}
export function wardenAcceptedDamage(c:WardenController,input:{attack:'jump-k'|'ultimate'|'stomp'|'throw'|'dash';bossX:number;playerX:number;playerY:number;cooldownMs:number}):number {if(!wardenVulnerable(c)||input.cooldownMs>0)return 0;const dx=Math.abs(input.playerX-input.bossX),dy=Math.abs(input.playerY-220);if((input.attack==='jump-k'||input.attack==='dash')&&wardenDashTouchesRibs(input.bossX,input.playerX,input.playerY))return WARDEN_RULES.damage.jumpK;if(input.attack==='ultimate'&&dx<=WARDEN_RULES.ultimateRangeX&&dy<=WARDEN_RULES.ultimateRangeY)return WARDEN_RULES.damage.ultimate;return 0;}
