import Phaser from 'phaser';
import {renderScale} from './renderScale';
import {projectMenuBoard,pullbackTarget,cameraAtProgress,restoreCamera,SpatialMenuTransition,gateMenuControls,bindMenuVisibilityLifecycle,spatialMenuLayout,menuPointer,menuGazeTarget,smoothMenuGaze,type MenuGaze,DemandMenuUpdates,menuDuckBacking,menuDuckSize,MenuDuckVisibility,menuBoardAngles,MENU_ZOOM_FACTOR,menuTransitionPhases} from './spatialMenuGeometry';
export {projectMenuBoard,pullbackTarget,cameraAtProgress,restoreCamera,SpatialMenuTransition,gateMenuControls,bindMenuVisibilityLifecycle,spatialMenuLayout} from './spatialMenuGeometry';
type CameraState={scrollX:number;scrollY:number;zoomX:number;zoomY:number;useBounds:boolean;lerpX:number;lerpY:number;visibility:boolean[]};type Pose={flipX:boolean;rotation:number;alpha:number;visible:boolean};
export class SpatialMenuPresentation {
 private visibility?:MenuDuckVisibility;private duck!:HTMLDivElement;private duckPose!:HTMLDivElement;private shadow!:HTMLDivElement;private duckWidth=66;private duckHeight=60;private originX=.5;private originY=.5;private gaze:MenuGaze={turn:0,tilt:-.12};private targetGaze:MenuGaze={turn:0,tilt:-.12};private closeGaze?:MenuGaze;private closeProgress=1;private demand!:DemandMenuUpdates;private hidden=false;private rect={left:0,top:0,width:640};private lastPointer?:{x:number;y:number};
 private readonly refreshRect=()=>{const r=document.querySelector<HTMLElement>('#game')?.getBoundingClientRect();if(r)this.rect={left:r.left,top:r.top,width:r.width};};
 private readonly pointerEnter=(event:PointerEvent)=>{this.refreshRect();this.pointerMove(event);};
 private readonly pointerMove=(event:PointerEvent)=>{if(!this.ready||this.hidden)return;const point=menuPointer(event.clientX,event.clientY,this.rect);if(this.lastPointer&&Math.hypot(point.x-this.lastPointer.x,point.y-this.lastPointer.y)<1)return;this.lastPointer=point;const center=this.duckCenter();this.targetGaze=menuGazeTarget(point.x-center.x,point.y-center.y,this.targetGaze.turn);this.wakeGaze();};
 private readonly neutral=()=>{this.lastPointer=undefined;this.targetGaze={turn:0,tilt:-.12};if(this.ready&&!this.hidden)this.wakeGaze();};
 private readonly updateGaze=(_time:number,delta:number)=>{this.gaze=smoothMenuGaze(this.gaze,this.targetGaze,delta,this.gaze);if(Math.abs(this.gaze.turn-this.targetGaze.turn)<.1&&Math.abs(this.gaze.tilt-this.targetGaze.tilt)<.0005){this.gaze.turn=this.targetGaze.turn;this.gaze.tilt=this.targetGaze.tilt;this.stopGaze();}this.renderPose();};
 private wakeGaze():void{if(this.disposed||!this.ready||this.hidden)return;this.demand.wake();}
 private stopGaze():void{this.demand?.stop();}
 private duckCenter(){return this.visual?{x:(this.visual.x-this.main.scrollX)*this.main.zoomX/renderScale(),y:(this.visual.y-this.main.scrollY)*this.main.zoomY/renderScale()}:{x:145,y:290};}
 private renderPose():void{const originalTurn=this.pose?.flipX?180:0,originalTilt=this.pose?.rotation??0;const p=menuTransitionPhases(this.transition.progress).zoomPhase;const blend=this.closing?Math.min(1,p/Math.max(.0001,this.closeProgress)):p;const pose=this.closing?(this.closeGaze??this.gaze):this.gaze;this.duckPose.style.transformOrigin=`${this.originX*100}% ${(this.originY+(.75-this.originY)*p)*100}%`;this.duckPose.style.transform=`rotate(${originalTilt+(pose.tilt-originalTilt)*blend}rad) rotateY(${originalTurn+(pose.turn-originalTurn)*blend}deg)`;}
 private createDuck(fallback?:HTMLImageElement|null):void{this.duck=document.createElement('div');this.duck.className='sm-duck-proxy';this.duckPose=document.createElement('div');this.duckPose.className='sm-duck-pose';this.shadow=document.createElement('div');this.shadow.className='sm-duck-shadow';if(this.visual){const v=this.visual,frame=v.frame,canvas=document.createElement('canvas');const backing=menuDuckBacking(v.displayWidth,v.displayHeight);canvas.width=backing.width;canvas.height=backing.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Menu duck canvas unavailable');ctx.drawImage(v.texture.getSourceImage() as CanvasImageSource,frame.cutX,frame.cutY,frame.cutWidth,frame.cutHeight,0,0,canvas.width,canvas.height);if(v.tintTopLeft!==0xffffff){ctx.globalCompositeOperation='multiply';ctx.fillStyle=`#${v.tintTopLeft.toString(16).padStart(6,'0')}`;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalCompositeOperation='destination-in';ctx.drawImage(v.texture.getSourceImage() as CanvasImageSource,frame.cutX,frame.cutY,frame.cutWidth,frame.cutHeight,0,0,canvas.width,canvas.height);ctx.globalCompositeOperation='source-over';}this.duckWidth=v.displayWidth;this.duckHeight=v.displayHeight;this.originX=v.originX;this.originY=v.originY;this.duckPose.append(canvas);}else if(fallback){fallback.className='';this.duckPose.append(fallback);}this.duck.append(this.duckPose);this.stage.append(this.shadow,this.duck);}

 readonly board:HTMLDivElement;private readonly stage:HTMLDivElement;private readonly wrapper:HTMLDivElement;private readonly parent:Phaser.Scene;private readonly main:Phaser.Cameras.Scene2D.Camera;private readonly visual?:Phaser.GameObjects.Image;private readonly start:CameraState;private readonly pose?:Pose;private tween?:Phaser.Tweens.Tween|null;private observer?:ResizeObserver;private readonly transition:SpatialMenuTransition;private disposed=false;private anchorX:number;private anchorY:number;private finalY=25;private onClosed?:()=>void;private readonly onPause=()=>this.hide();private readonly onSleep=()=>this.hide();private readonly onResume=()=>this.show();private readonly onWake=()=>this.show();private readonly onDestroy=()=>this.destroy();private unbindVisibility?:()=>void;
 constructor(private readonly menu:Phaser.Scene,parent:Phaser.Scene|undefined,content:string,private readonly onReady?:()=>void){this.demand=new DemandMenuUpdates(()=>this.menu.events.on(Phaser.Scenes.Events.UPDATE,this.updateGaze),()=>this.menu.events.off(Phaser.Scenes.Events.UPDATE,this.updateGaze));this.parent=parent??menu;this.main=this.parent.cameras.main;const player=(this.parent as unknown as {player?:{visual?:Phaser.GameObjects.Image}}).player;this.visual=player?.visual;if(this.visual)this.visibility=new MenuDuckVisibility(this.visual,()=>!!this.visual&&this.visual.scene===this.parent&&!this.visual.isDestroyed);this.transition=new SpatialMenuTransition(!this.visual);this.start={scrollX:this.main.scrollX,scrollY:this.main.scrollY,zoomX:this.main.zoomX/renderScale(),zoomY:this.main.zoomY/renderScale(),useBounds:this.main.useBounds,lerpX:this.main.lerp.x,lerpY:this.main.lerp.y,visibility:this.parent.cameras.cameras.map(c=>!!c.visible)};this.pose=this.visual?{flipX:this.visual.flipX,rotation:this.visual.rotation,alpha:this.visual.alpha,visible:this.visual.visible}:undefined;
  if(this.visual){this.anchorX=this.visual.x+100/(this.start.zoomX*MENU_ZOOM_FACTOR);this.anchorY=this.visual.y-265/(this.start.zoomY*MENU_ZOOM_FACTOR);}else{this.anchorX=this.main.scrollX+245/(this.start.zoomX*MENU_ZOOM_FACTOR);this.anchorY=this.main.scrollY+this.finalY/(this.start.zoomY*MENU_ZOOM_FACTOR);this.main.setZoom(this.start.zoomX*MENU_ZOOM_FACTOR*renderScale(),this.start.zoomY*MENU_ZOOM_FACTOR*renderScale());}
  this.main.setLerp(0,0);this.main.useBounds=false;this.parent.cameras.cameras.forEach((c,i)=>{if(i>0)c.setVisible(false);});const game=document.querySelector<HTMLElement>('#game');if(!game)throw new Error('Spatial menu requires #game');this.stage=document.createElement('div');this.stage.className=`spatial-menu-stage${this.visual?'':' fallback'}`;this.wrapper=document.createElement('div');this.wrapper.className='spatial-menu-anchor';this.board=document.createElement('div');this.board.className='spatial-menu-board';const assetRoot=`${import.meta.env.BASE_URL||'/'}assets/menu/royal-ui-v1/`;for(const [name,file] of Object.entries({surface:'menu-surface.webp',primary:'button-primary.webp',continue:'button-continue.webp',replay:'button-replay.webp',journal:'button-journal.webp',routes:'button-routes.webp',trials:'button-trials.webp',graphics:'button-graphics.webp',previous:'button-previous.webp',next:'button-next.webp'}))this.board.style.setProperty(`--sm-art-${name}`,`url('${assetRoot}${file}')`);this.board.style.setProperty('--sm-stone',`url('${import.meta.env.BASE_URL||'/'}assets/gate3/masonry.png')`);this.board.innerHTML=content;const fallbackWorld=this.board.querySelector<HTMLElement>('.sm-world'),fallbackDuck=this.board.querySelector<HTMLImageElement>('.sm-fallback-duck');fallbackWorld?.remove();fallbackDuck?.remove();if(fallbackWorld)this.stage.append(fallbackWorld);this.wrapper.append(this.board);this.stage.append(this.wrapper);this.createDuck(fallbackDuck);game.append(this.stage);const resize=()=>{this.refreshRect();this.stage.style.transform=`scale(${game.clientWidth/640})`;const layout=spatialMenuLayout(game.clientWidth);this.stage.classList.toggle('narrow',layout.narrow);const nextY=layout.finalY;if(nextY!==this.finalY){this.finalY=nextY;this.anchorY=this.visual?this.visual.y+(this.finalY-290)/(this.start.zoomY*MENU_ZOOM_FACTOR):this.main.scrollY+this.finalY/(this.start.zoomY*MENU_ZOOM_FACTOR);}this.project();};this.observer=new ResizeObserver(resize);this.observer.observe(game);resize();this.visibility?.conceal();this.board.addEventListener('pointerenter',this.pointerEnter);this.board.addEventListener('pointermove',this.pointerMove);this.board.addEventListener('pointerleave',this.neutral);window.addEventListener('blur',this.neutral);window.addEventListener('resize',this.refreshRect);window.addEventListener('scroll',this.refreshRect,true);this.menu.events.once(Phaser.Scenes.Events.SHUTDOWN,this.onDestroy);this.menu.events.once(Phaser.Scenes.Events.DESTROY,this.onDestroy);this.unbindVisibility=bindMenuVisibilityLifecycle(this.menu.events,this.onPause,this.onSleep,this.onResume,this.onWake);this.syncControls();if(this.visual)this.animate(1,940,()=>{this.transition.markReady();this.syncControls();this.onReady?.();});}
 get ready():boolean{return this.transition.canAct;}get closing():boolean{return this.transition.closing;}
 syncControls():void{gateMenuControls(Array.from(this.board.querySelectorAll<HTMLButtonElement>('button[data-action]')),this.ready);}
 close(done?:()=>void):void{if(this.disposed)return;const duration=this.transition.beginClose();if(duration===undefined)return;const closeZoom=menuTransitionPhases(this.transition.progress).zoomPhase;this.closeGaze={turn:(this.pose?.flipX?180:0)+(this.gaze.turn-(this.pose?.flipX?180:0))*closeZoom,tilt:(this.pose?.rotation??0)+(this.gaze.tilt-(this.pose?.rotation??0))*closeZoom};this.closeProgress=closeZoom;this.stopGaze();this.syncControls();this.board.querySelector<HTMLElement>('.sm-board-inner')?.focus();this.onClosed=done;this.animate(0,duration,()=>{if(!this.transition.finishClose())return;this.restore();this.onClosed?.();});}
 private animate(to:number,duration:number,complete:()=>void):void{this.tween?.stop();const from=this.transition.progress;this.tween=this.menu.tweens.addCounter({from,to,duration,ease:'Linear',onUpdate:t=>{this.transition.setProgress(t.getValue()??this.transition.progress);this.apply();},onComplete:complete});}
 private apply():void{if(this.visual&&(this.visual.scene!==this.parent||this.visual.isDestroyed||!this.parent.cameras?.cameras.includes(this.main)))return;const zoomPhase=menuTransitionPhases(this.transition.progress).zoomPhase;const qx=Phaser.Math.Linear(this.start.zoomX,this.start.zoomX*MENU_ZOOM_FACTOR,zoomPhase),qy=Phaser.Math.Linear(this.start.zoomY,this.start.zoomY*MENU_ZOOM_FACTOR,zoomPhase),target=pullbackTarget(this.visual?.x??this.start.scrollX+320/this.start.zoomX,this.visual?.y??this.start.scrollY+200/this.start.zoomY,this.start.zoomX*MENU_ZOOM_FACTOR,this.start.zoomY*MENU_ZOOM_FACTOR);const camera=cameraAtProgress(this.start.scrollX,this.start.scrollY,this.start.zoomX,this.start.zoomY,target.scrollX,target.scrollY,this.start.zoomX*MENU_ZOOM_FACTOR,this.start.zoomY*MENU_ZOOM_FACTOR,zoomPhase,renderScale());this.main.setZoom(camera.zoomX,camera.zoomY).setScroll(camera.scrollX,camera.scrollY);this.project(qx,qy);}
 private project(qx=this.main.zoomX/renderScale(),qy=this.main.zoomY/renderScale()):void{const phases=menuTransitionPhases(this.transition.progress);const p=projectMenuBoard(this.anchorX,this.anchorY,this.main.scrollX,this.main.scrollY,qx,qy,this.start.zoomX*MENU_ZOOM_FACTOR,this.start.zoomY*MENU_ZOOM_FACTOR);this.wrapper.style.left=`${p.x}px`;this.wrapper.style.top=`${p.y}px`;this.wrapper.style.transform=`scale(${p.scaleX},${p.scaleY})`;const center=this.duckCenter(),{width,height}=menuDuckSize(this.duckWidth,this.duckHeight,this.start.zoomX,this.start.zoomY,phases.zoomPhase,!!this.visual);this.duck.style.left=`${center.x-width*this.originX}px`;this.duck.style.top=`${center.y-height*this.originY}px`;this.duck.style.width=`${width}px`;this.duck.style.height=`${height}px`;this.duck.style.opacity=String(this.pose?.alpha??1);this.duck.style.visibility=this.pose?.visible===false?'hidden':'visible';this.shadow.style.width=`${width*.72}px`;this.shadow.style.height='10px';this.shadow.style.left=`${center.x-width*.36}px`;this.shadow.style.top=`${center.y+height*(1-this.originY)-4}px`;this.shadow.style.opacity=String(phases.zoomPhase);this.renderPose();const angles=menuBoardAngles(phases.revealPhase);this.board.style.transform=`rotateZ(${angles.z}deg) rotateY(${angles.y}deg)`;this.board.style.opacity=String(phases.revealPhase);}
 private hide():void{this.hidden=true;this.stopGaze();this.stage.style.display='none';}private show():void{this.hidden=false;this.stage.style.display='';this.refreshRect();this.neutral();this.project();}
 private restore():void{this.visibility?.restore();this.duck.style.visibility='hidden';const systems=(this.parent as unknown as {sys?:{settings?:{key?:string}}}).sys,key=systems?.settings?.key;if(!key)return;const manager=(this.menu as unknown as {scene?:{isActive?:(key:string)=>boolean;isPaused?:(key:string)=>boolean}}).scene;if(this.parent!==this.menu&&(!manager?.isActive?.(key)&&!manager?.isPaused?.(key)))return;const cameras=(this.parent as unknown as {cameras?:{cameras?:Phaser.Cameras.Scene2D.Camera[]}}).cameras?.cameras;if(!cameras?.includes(this.main))return;const restored=restoreCamera(this.start,renderScale());this.main.setZoom(restored.zoomX,restored.zoomY).setScroll(restored.scrollX,restored.scrollY).setLerp(restored.lerpX,restored.lerpY);this.main.useBounds=restored.useBounds;cameras.forEach((c,i)=>c.setVisible(restored.visibility[i]??true));if(this.visual&&this.pose&&this.visual.scene===this.parent&&!this.visual.isDestroyed)this.visual.setFlipX(this.pose.flipX).setRotation(this.pose.rotation).setAlpha(this.pose.alpha);}
 destroy():void{if(this.disposed)return;this.disposed=true;this.stopGaze();this.board.removeEventListener('pointerenter',this.pointerEnter);this.board.removeEventListener('pointermove',this.pointerMove);this.board.removeEventListener('pointerleave',this.neutral);window.removeEventListener('blur',this.neutral);window.removeEventListener('resize',this.refreshRect);window.removeEventListener('scroll',this.refreshRect,true);this.unbindVisibility?.();this.unbindVisibility=undefined;const events=(this.menu as unknown as {events?:Phaser.Events.EventEmitter}).events;events?.off(Phaser.Scenes.Events.SHUTDOWN,this.onDestroy);events?.off(Phaser.Scenes.Events.DESTROY,this.onDestroy);this.tween?.stop();this.observer?.disconnect();this.restore();this.stage.remove();this.transition.finishClose();}
}
