import Phaser from 'phaser';
import {loadProgress} from '../systems/progress';
import {chapterSections,type ChapterKind} from '../data/chapters';
import {setupRenderScale} from '../systems/renderScale';
const chapters=[{id:'gate-1',name:'ROYAL HALL'},{id:'jail',name:'SUNKEN CELLS'},{id:'outside',name:'WILDLANDS'},{id:'crimson',name:'CRIMSON THRONE'}] as const;
const gateLore=['Fractured Royal Stone|A committed dash shatters weakened masonry. Sound pillars throw you back.','Archive Seal|A cracked seal concealed a forgotten alcove in the royal hall.','Eastern Masonry|Three hidden alcoves remain in the royal hall. Their weakened seals bear the same fractures.'];
export class JournalScene extends Phaser.Scene {
 private chapter=0;private page=0;private content!:Phaser.GameObjects.Container;private counter!:Phaser.GameObjects.Text;private hint!:Phaser.GameObjects.Text;
 constructor(){super('journal');}
 create():void {this.cameras.main.setBackgroundColor(0x090d12);this.add.rectangle(320,200,640,400,0x101722).setStrokeStyle(2,0x71572f);this.add.text(320,22,'FIELD JOURNAL',{fontFamily:'Georgia',fontSize:'21px',color:'#f1d18d'}).setOrigin(.5);chapters.forEach((c,i)=>this.button(84+i*157,62,c.name,()=>{this.chapter=i;this.page=0;this.render();},116));this.hint=this.add.text(320,87,'',{fontSize:'9px',color:'#afa98f'}).setOrigin(.5);this.content=this.add.container(0,0);this.counter=this.add.text(320,319,'',{fontSize:'9px',color:'#aaa'}).setOrigin(.5);this.button(90,342,'‹ PREVIOUS',()=>{this.page=Math.max(0,this.page-1);this.render();},110);this.button(550,342,'NEXT ›',()=>{this.page++;this.render();},90);this.button(320,374,'BACK',()=>this.back(),90);this.render();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){this.back();return;}if(e.key==='ArrowRight'){this.page++;this.render();}if(e.key==='ArrowLeft'){this.page=Math.max(0,this.page-1);this.render();}if(['1','2','3','4'].includes(e.key)){this.chapter=Number(e.key)-1;this.page=0;this.render();}};this.input.keyboard?.on('keydown',key);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.input.keyboard?.off('keydown',key));setupRenderScale(this,'menu-hud');this.cameras.main.ignore(this.children.list);}
 private render():void {this.content.removeAll(true);const scene=chapters[this.chapter].id,progress=loadProgress().chapters[scene],entries=scene==='gate-1'?gateLore.map((s,i)=>({id:i,...Object.fromEntries((s.split('|') as [string,string]).map((v,j)=>[j?'lore':'name',v])) as {name:string;lore:string}})):chapterSections(scene as ChapterKind).flatMap((s,i)=>s.secret?[{id:i,name:s.name,lore:s.secret}]:[]);const maxPage=Math.max(0,Math.ceil(entries.length/4)-1);this.page=Math.min(this.page,maxPage);const page=entries.slice(this.page*4,this.page*4+4);this.hint.setText(progress.discoveries.length===0?'Find hidden paths to uncover stories for this chapter.':'');page.forEach((entry,i)=>{const found=progress.discoveries.includes(entry.id),y=107+i*52;this.content.add(this.add.text(104,y,found?entry.name:'Undiscovered',{fontFamily:'Georgia',fontSize:'12px',color:found?'#f1d18d':'#8e9292'}));if(found)this.content.add(this.add.text(104,y+18,entry.lore,{fontFamily:'Georgia',fontSize:'10px',color:'#c7c3b4',wordWrap:{width:430}}));});this.counter.setText(`${this.page+1} / ${maxPage+1}`);}
 private button(x:number,y:number,label:string,action:()=>void,width:number):void {this.add.text(x,y,label,{fontFamily:'Georgia',fontSize:'9px',color:'#fff0cc',backgroundColor:'#352716',padding:{x:6,y:5},align:'center'}).setOrigin(.5).setFixedSize(width,22).setInteractive({useHandCursor:true}).on('pointerdown',action);}
 private back():void {this.scene.stop();this.scene.resume('menu');}
}
