import Phaser from 'phaser';
import {loadProgress,saveProgress,resetChapter,sceneDataFromProgress,canPracticeBoss,canPersistCampaign,type CampaignScene} from '../systems/progress';
import {renderQuality,setRenderQuality} from '../systems/renderScale';
import type {RenderQuality} from '../systems/performancePolicy';
import {resetCampaignRunEligibility,campaignRunEligible} from '../systems/debug/debugSettings';
import {chapterSections,type ChapterKind} from '../data/chapters';
import {preloadSceneAssets} from './SceneAssets';
import {SpatialMenuPresentation} from '../systems/SpatialMenuPresentation';
const cards:{key:CampaignScene;name:string;art:string}[]=[{key:'gate-1',name:'Corrupted Kingdom',art:'ruined-kingdom.webp'},{key:'jail',name:'Sunken Cells',art:'jail-gallery.webp'},{key:'outside',name:'Wildlands',art:'wildwood.webp'},{key:'crimson',name:'Crimson Throne',art:'crimson-crab.webp'},{key:'rescue',name:'Hollow Prison',art:'cistern.webp'}];
export class MenuScene extends Phaser.Scene {
 private pausedScene?:string;private selection=0;private resumeAction!:()=>void;private presentation?:SpatialMenuPresentation;private keydown?: (e:KeyboardEvent)=>void;private actionTaken=false;private readonly onMenuResume=()=>{this.actionTaken=false;this.presentation?.board.querySelector<HTMLElement>('.sm-board-inner')?.focus();this.presentation?.syncControls();};
 constructor(){super('menu');}preload():void{preloadSceneAssets(this,'menu');}
 create(data:{pausedScene?:string}={}):void{this.pausedScene=data.pausedScene;this.selection=0;this.actionTaken=false;this.resumeAction=()=>this.closeResume();this.cameras.main.setAlpha(0);const parent=this.pausedScene&&this.scene.isPaused(this.pausedScene)?this.game.scene.getScene(this.pausedScene):undefined;const base=import.meta.env.BASE_URL||'/';this.presentation=new SpatialMenuPresentation(this,parent,this.content(base),()=>this.presentation?.syncControls());const ownedBoard=this.presentation.board;ownedBoard.addEventListener('click',this.onClick);ownedBoard.querySelector<HTMLElement>('.sm-board-inner')?.focus();
  this.keydown=(e)=>{if(e.repeat||this.actionTaken||this.scene.isPaused())return;const key=e.key.toLowerCase();if(key==='escape'){e.preventDefault();if(this.pausedChapterIsValid())this.closeResume();else if(this.presentation?.ready)this.runPrimaryAction();return;}if(!this.presentation?.ready)return;if(key==='arrowright'||key==='arrowdown'){e.preventDefault();this.selection=(this.selection+1)%cards.length;this.updateSelection();}else if(key==='arrowleft'||key==='arrowup'){e.preventDefault();this.selection=(this.selection+cards.length-1)%cards.length;this.updateSelection();}else if(key==='enter'&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();this.openChapter(cards[this.selection].key,false);}else if(key==='r'){e.preventDefault();this.openChapter(cards[this.selection].key,true);}else if(key==='j'){e.preventDefault();this.openJournal();}else if(key==='p'){e.preventDefault();this.openRouteSelect(0);}else if(key==='g'){e.preventDefault();this.openPractice('regent-practice','outside');}else if(key==='c'){e.preventDefault();this.openPractice('crab-practice','crimson');}else if(key==='q'){e.preventDefault();this.toggleGraphics();}};const ownedKeydown=this.keydown;ownedBoard.addEventListener('keydown',ownedKeydown);this.events.on(Phaser.Scenes.Events.RESUME,this.onMenuResume);let cleaned=false;const cleanup=()=>{if(cleaned)return;cleaned=true;this.events.off(Phaser.Scenes.Events.RESUME,this.onMenuResume);this.events.off(Phaser.Scenes.Events.SHUTDOWN,cleanup);this.events.off(Phaser.Scenes.Events.DESTROY,cleanup);ownedBoard.removeEventListener('click',this.onClick);ownedBoard.removeEventListener('keydown',ownedKeydown);};this.events.once(Phaser.Scenes.Events.SHUTDOWN,cleanup);this.events.once(Phaser.Scenes.Events.DESTROY,cleanup);}
 private onClick=(event:Event):void=>{if(!this.presentation?.ready||this.actionTaken)return;const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;this.act(button.dataset.action??'');};
 private content(base:string):string{const p=loadProgress(),items=cards.map((c,i)=>{const unlocked=p.unlocked.includes(c.key),complete=p.completed.includes(c.key),count=p.chapters[c.key].discoveries.length,total=c.key==='gate-1'?3:c.key==='rescue'?0:chapterSections(c.key as ChapterKind).filter(s=>s.secret).length,status=c.key==='rescue'?`FRANKLIN · ${p.chapters.rescue.bossDefeated?'SAVED':p.chapters.rescue.opened.includes(0)?'RELEASED':'CHAINED'}`:unlocked?`DISCOVERIES · ${count}/${total}${complete?' · COMPLETE':''}`:`LOCKED · ${cards[i-1]?.name??'BEGIN JOURNEY'}`;return `<article class="sm-chapter ${i===0?'selected':''}" data-chapter="${i}"><img src="${base}assets/menu/cards/${c.art}" alt=""><div class="sm-num">CHAPTER ${i+1}</div><div class="sm-name">${c.name}</div><div class="sm-status">${status}</div><div class="sm-pair"><button class="sm-continue" data-action="continue:${c.key}" ${unlocked?'':'disabled data-locked="true"'}>CONTINUE</button><button class="sm-replay" data-action="replay:${c.key}" ${unlocked?'':'disabled data-locked="true"'}>REPLAY</button></div></article>`;}).join('');return `<div class="sm-world" style="background-image:url('${base}assets/menu/cards/ruined-kingdom.webp')"></div><div class="sm-board-inner" tabindex="0"><i class="sm-support sm-support-left"></i><i class="sm-support sm-support-right"></i><header><div class="sm-title">THE CROWN ROAD</div><div class="sm-subtitle">A Duckoman Rebirth campaign</div></header><img class="sm-fallback-duck" src="${base}assets/gate3/duckoman.png" alt=""><section class="sm-chapters">${items}</section><button class="sm-prev" aria-label="Previous chapter" data-action="select-prev">‹</button><button class="sm-next" aria-label="Next chapter" data-action="select-next">›</button><div class="sm-index">1 / 5</div><button class="sm-primary" data-action="primary">${this.primaryActionLabel(p)}</button><div class="sm-utilities"><button class="sm-journal" data-action="journal">JOURNAL</button><button class="sm-routes" data-action="routes">ROUTE PRACTICE</button><button class="sm-trials" data-action="trials">BOSS TRIALS</button><button class="sm-graphics" data-action="graphics">${this.graphicsLabel()}</button></div><footer><span class="sm-footer-wide">ARROWS · SELECT &nbsp; ENTER · CONTINUE &nbsp; R · REPLAY &nbsp; ESC · RETURN</span><span class="sm-footer-narrow">ESC · RETURN</span></footer></div>`;}
 private act(action:string):void{if(action==='select-prev'||action==='select-next'){this.selection=(this.selection+(action==='select-next'?1:cards.length-1))%cards.length;this.updateSelection();return;}if(action==='primary'){this.runPrimaryAction();return;}if(action==='journal'){this.actionTaken=true;this.openJournal();return;}if(action==='routes'){this.actionTaken=true;this.openRouteSelect(0);return;}if(action==='trials'){this.actionTaken=true;this.openRouteSelect(3);return;}if(action==='graphics'){this.toggleGraphics();return;}const [kind,key]=action.split(':');if((kind==='continue'||kind==='replay')&&key)this.openChapter(key as CampaignScene,kind==='replay');}
 private updateSelection():void{this.presentation?.board.querySelectorAll<HTMLElement>('.sm-chapter').forEach((el,i)=>el.classList.toggle('selected',i===this.selection));const label=this.presentation?.board.querySelector<HTMLElement>('.sm-index');if(label)label.textContent=`${this.selection+1} / 5`;}
 private pausedChapterIsValid():boolean{return !!this.pausedScene&&this.scene.isPaused(this.pausedScene);}
 private primaryActionLabel(p:ReturnType<typeof loadProgress>):string{return this.pausedChapterIsValid()?'RESUME JOURNEY':p.ended?'REPLAY CAMPAIGN':hasProgress(p)?'CONTINUE JOURNEY':'BEGIN JOURNEY';}
 private runPrimaryAction():void{if(this.pausedChapterIsValid()){this.resumeAction();return;}const p=loadProgress();if(p.ended){this.openChapter('gate-1',true);return;}if(!this.pausedScene&&!hasProgress(p)){this.openChapter('gate-1',true);return;}this.actionTaken=true;this.scene.start(p.currentScene,sceneDataFromProgress(p,p.currentScene));}
 private closeResume():void{if(!this.pausedScene||!this.scene.isPaused(this.pausedScene)||this.actionTaken)return;this.actionTaken=true;this.presentation?.close(()=>{if(!this.pausedScene)return;const key=this.pausedScene;this.scene.setVisible(true,key);this.scene.stop();this.scene.resume(key);this.game.canvas.focus();});}
 private graphicsLabel():string{return renderQuality()==='smooth'?'GRAPHICS SMOOTH':'GRAPHICS SHARP';}private toggleGraphics():void{const q:RenderQuality=renderQuality()==='smooth'?'sharp':'smooth';setRenderQuality(q,this.game);const b=this.presentation?.board.querySelector<HTMLButtonElement>('.sm-graphics');if(b)b.textContent=this.graphicsLabel();}
 private openJournal():void{this.scene.pause();this.scene.launch('journal');this.scene.bringToTop('journal');}private openRouteSelect(tab:number):void{this.scene.pause();this.scene.launch('routes',{pausedScene:this.pausedScene,tab});this.scene.bringToTop('routes');}
 private openPractice(key:'regent-practice'|'crab-practice',chapter:'outside'|'crimson'):void{if(!canPracticeBoss(loadProgress(),chapter))return;if(this.pausedScene&&this.scene.isPaused(this.pausedScene))this.scene.stop(this.pausedScene);this.pausedScene=undefined;this.registry.set('devPreview',false);this.scene.start(key,{practice:true});}
 private openChapter(scene:CampaignScene,replay:boolean):void{const p=loadProgress();if(!p.unlocked.includes(scene))return;this.actionTaken=true;if(this.pausedScene&&this.scene.isPaused(this.pausedScene))this.scene.stop(this.pausedScene);this.registry.set('devPreview',false);if(replay)resetCampaignRunEligibility();if(scene==='rescue'&&!canPersistCampaign({runEligible:campaignRunEligible()})){if(replay)this.scene.start('rescue',{devPreview:true,freshReplay:true});else this.scene.start('rescue',{...sceneDataFromProgress(p,'rescue')});return;}const next=replay?resetChapter(p,scene):p;next.currentScene=scene;next.ended=false;saveProgress(next);this.scene.start(scene,{...sceneDataFromProgress(next,scene),freshReplay:replay});}
}
function hasProgress(p:ReturnType<typeof loadProgress>):boolean{return p.completed.length>0||p.unlocked.length>1||Object.values(p.chapters).some(c=>c.checkpoint>0||c.charge>0||c.secrets.length||c.opened.length||c.bossDefeated);}
